version: '3.8'

services:
  web:
    build: ./requirements/
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    ports:
      - "80:8000"
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge
