# Generated by Django 4.1.13 on 2024-07-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_barcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
