# Generated by Django 4.1.13 on 2024-07-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_barcode', '0002_alter_formdata_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdata',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='formdata',
            name='lname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formdata',
            name='tel',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
