# Generated by Django 4.1.13 on 2024-07-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_barcode', '0003_rename_name_formdata_fname_formdata_lname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='tel',
            field=models.CharField(max_length=13),
        ),
    ]
