# Generated by Django 4.1.13 on 2024-07-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_barcode', '0004_alter_formdata_tel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormData',
            new_name='client',
        ),
    ]
