# Generated by Django 4.1.13 on 2024-07-26 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_barcode', '0005_formdata_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='reset_password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('signed_token', models.CharField(max_length=100)),
                ('time_created', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AddField(
            model_name='formdata',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
