# Generated by Django 4.1.13 on 2024-07-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_barcode', '0005_rename_formdata_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='client',
            new_name='FormData',
        ),
    ]
