# Generated by Django 4.1.13 on 2024-07-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_barcode', '0006_reset_password_formdata_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='password',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
