# Generated by Django 4.1.13 on 2024-07-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_barcode', '0007_formdata_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reset_password',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
