# Generated by Django 4.1.13 on 2024-07-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_barcode', '0006_rename_client_formdata'),
        ('manage_barcode', '0008_alter_reset_password_time_created'),
    ]

    operations = [
    ]
