# Generated by Django 4.1.13 on 2024-07-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_barcode', '0011_remove_formdata_password_formdata_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='ticket_number',
        ),
    ]
