# Generated by Django 4.1.13 on 2024-07-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_barcode', '0012_remove_tickets_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='manage_barcode.formdata'),
        ),
    ]
