# Generated by Django 4.1.13 on 2024-07-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_barcode', '0013_alter_tickets_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='manage_barcode.formdata'),
        ),
    ]
