# Generated by Django 4.1.13 on 2024-07-30 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_barcode', '0015_photo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_data',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='manage_barcode.formdata'),
        ),
    ]
