# Generated by Django 4.1.13 on 2024-07-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_barcode', '0016_photo_data_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_data',
            name='path',
            field=models.TextField(default=''),
        ),
    ]
