# Generated by Django 4.1.13 on 2024-07-30 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_barcode', '0017_photo_data_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_data',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manage_barcode.formdata'),
        ),
    ]
