# Generated by Django 4.1.13 on 2024-07-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_barcode', '0018_alter_photo_data_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_data',
            name='path',
            field=models.TextField(default=None),
        ),
    ]
