# Generated by Django 4.1.13 on 2024-07-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_barcode', '0019_alter_photo_data_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo_data',
            name='path',
        ),
    ]
