# Generated by Django 4.1.13 on 2024-07-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_barcode', '0020_remove_photo_data_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='path_avatar',
            field=models.TextField(default='/static//media/profile.jpg'),
        ),
        migrations.DeleteModel(
            name='Photo_data',
        ),
    ]
