# Generated by Django 4.1.13 on 2024-07-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_barcode', '0021_formdata_path_avatar_delete_photo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='path_avatar',
            field=models.TextField(default='/static/media/profile.jpg'),
        ),
    ]
