# Generated by Django 4.1.13 on 2024-08-06 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_barcode', '0022_alter_formdata_path_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.IntegerField()),
                ('depart_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('travel_time', models.IntegerField()),
                ('number_of_buses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=100)),
                ('terminus', models.BooleanField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ord_stat', to='manage_barcode.bus')),
            ],
        ),
        migrations.DeleteModel(
            name='reset_password',
        ),
        migrations.AddField(
            model_name='bus',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='manage_barcode.city'),
        ),
    ]
