# Generated by Django 4.1.13 on 2024-08-09 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage_barcode', '0023_bus_city_station_delete_reset_password_bus_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
