# Generated by Django 4.1.13 on 2024-08-09 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage_barcode', '0026_alter_formdata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
